/***
 * Event type definitions.
 */
#pragma once

/**
 * Block device events.
 */
#define EVENT_BLOCK_DEVICE 0x1000

#define EVENT_BLOCK_DEVICE_INITIALIZED (EVENT_BLOCK_DEVICE + 0x01)
#define EVENT_BLOCK_DEVICE_PARTITION_PROBE (EVENT_BLOCK_DEVICE + 0x02)
#define EVENT_BLOCK_DEVICE_DESTROYING (EVENT_BLOCK_DEVICE + 0x03)
#define EVENT_BLOCK_DEVICE_DESTROYED (EVENT_BLOCK_DEVICE + 0x04)

/**
 * Network Interface events.
 */
#define EVENT_NETWORK_IFACE 0x2000
#define EVENT_NETWORK_IFACE_SUBSYSTEM_INIT (EVENT_NETWORK_IFACE + 0x01)
#define EVENT_NETWORK_IFACE_REGISTERED (EVENT_NETWORK_IFACE + 0x02)
#define EVENT_NETWORK_IFACE_DESTROYING (EVENT_NETWORK_IFACE + 0x03)
#define EVENT_NETWORK_IFACE_DESTROYED (EVENT_NETWORK_IFACE + 0x04)

/**
 * Network Stack events.
 */
#define EVENT_NETWORK_STACK 0x3000
#define EVENT_NETWORK_STACK_IFACE_UP (EVENT_NETWORK_STACK + 0x01)
#define EVENT_NETWORK_STACK_IFACE_DOWN (EVENT_NETWORK_STACK + 0x02)
#define EVENT_NETWORK_STACK_IFACE_UPDATE (EVENT_NETWORK_STACK + 0x03)
#define EVENT_NETWORK_STACK_IPV4_PKT_RECEIVE (EVENT_NETWORK_STACK + 0x04)
#define EVENT_NETWORK_STACK_IPV4_PKT_SEND (EVENT_NETWORK_STACK + 0x05)
#define EVENT_NETWORK_STACK_RAW_PKT_RECEIVE (EVENT_NETWORK_STACK + 0x06)
#define EVENT_NETWORK_STACK_RAW_PKT_SEND (EVENT_NETWORK_STACK + 0x07)

/**
 * Device Registry events.
 */
#define EVENT_DEVICE 0x4000
#define EVENT_DEVICE_REGISTERED (EVENT_DEVICE + 0x01)
#define EVENT_DEVICE_UNREGISTERED (EVENT_DEVICE + 0x02)

/**
 * Driver events.
 */
#define EVENT_DRIVER 0x5000
#define EVENT_DRIVER_SETUP (EVENT_DRIVER + 0x01)
