#pragma once

#define DEVICE_CLASS_UNKNOWN 0x01
#define DEVICE_CLASS_ROOT 0x02
#define DEVICE_CLASS_PCI 0x03
#define DEVICE_CLASS_NETWORK 0x04
#define DEVICE_CLASS_INPUT 0x05
#define DEVICE_CLASS_BLOCK 0x06
#define DEVICE_CLASS_FRAMEBUFFER 0x07
#define DEVICE_CLASS_USB_CONTROLLER 0x08
